name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: [self-hosted, hani]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify tools
        run: |
          git --version
          terraform --version

      - name: Terraform Init
        working-directory: ./Day-1-vpc-creation
        run: terraform init

      - name: Terraform Plan
        working-directory: ./Day-1-vpc-creation
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./Day-1-vpc-creation
        run: terraform apply -auto-approve
